default:
    adapter: mysql2
    database: cats
    username: cat_rescue
    password: w0rk5pac3
    host: localhost
development:
    adapter: mysql2
    database: cats
    username: cat_rescue
    password: w0rk5pac3
    host: localhost
production:
    adapter: mysql2
    database: cats
    username: cat_rescue
    password: w0rk5pac3
    host: localhost